name: Automating Text Extraction

on:
  push:
    branches:
      - main
    path-ignore:
      - "README.md"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      # Step 1: Check out the code
      - name: Checkout the code
        uses: actions/checkout@v3

      # Step 2: Set up QEMU and Docker Buildx
      - name: Set up QEMU for cross-platform builds
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm64

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Cache Docker Layers to speed up builds
      - name: Cache Docker Layers
        uses: actions/cache@v3
        with:
          path: ~/.docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      # Step 6: Build Docker image and push
      - name: Build Docker image and push
        run: |
          TIMESTAMP=$(date +%Y%m%d%H)  # Unique timestamp format with seconds
          docker buildx build --platform linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/open-source-python:latest --push .
