name: Automating Text Extraction

on:
  push:
    branches:
      - main
    path-ignore:
      - "README.md"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD }}

    steps:
      # Step 1: Check out the code
      - name: Checkout the code
        uses: actions/checkout@v3

      # Step 2: Set up QEMU and Docker Buildx
      - name: Set up QEMU for cross-platfrom builds
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm64

      # Step 3: set up docker buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Login in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: $${{secrets.DOCKER_PASSWORD}}

      # Step 5: Cache Docker Layers to speed up builds
      - name: Cache Docker Layers
        uses: actions/cache@v3
        with:
          path:
