name: Automating Text Extraction

on:
  push:
    branches:
      - main
    path-ignore:
      - "README.md"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - name: Checkout the code
        uses: actions/checkout@v3
